### ISSUE TITLE
replaceAndRemove is allocating space when the question explicitly says you can't

### ISSUE THREAD

**Issue by McFlurriez** [epibook/epibook.github.io#24]
Note that in the solution for replaceAndRemove, you have:

    // Allocates space according to the number of "a".
    sChars = Arrays.copyOf(sChars, writeIdx + aCount);

From the Javadocs I see:

Returns:
a copy of the original array, truncated or padded with null characters to obtain the specified length

I think utilizing this in the question when the question is about doing everything in place defeats the purpose. It also masks the issue of nullifying characters that extend past the the end of array if there are more b's than a's.

Thoughts?

Thanks,
Anthony

**Comment by epibook** [comment]
thanks for pointing that out,  you are right the code is not O(1) space.

simply deleting that line solves the problem.

i noticed the tests are broken, since they do not ensure that the inputs
have enough space (e.g., "aaabb".toCharArray() will not have enough space
to do the transformation (since we need 6 chars but the array is of length
5)

the c++ uses resize which is fine if the input is valid. the bug was
introduced in the translation, i have updated the code, still need to
update the tests.

bye,
adnan

**Comment by McFlurriez** [comment]
Agreed, I noticed that too. Thanks Adnan!
