### ISSUE TITLE
Java Heap programs not using Heap

### ISSUE THREAD

**Issue by kellyfj** [epibook/epibook.github.io#5]
I don't see any heap data structures in 

https://github.com/epibook/epibook.github.io/blob/master/solutions/java/src/main/java/com/epi/CompareKthLargestInHeap.java

It works but it's not really a heap I think?

Suggest you use a java.util.PriorityQueue (which is what folks use in Java for a Heap - but it grows automatically) or create your own fixed size priority queue.  I can submit a proposed patch if you will take a Pull Request?

Best,

-Frank

**Comment by tsunghsienlee** [comment]
Hey Frank,

In this problem, we are discussing a heap which is represented as an array, so that is the reason we use an array here. Besides, if you use a priority queue, there is no way you can explicitly traverse this heap (i.e., left child of an node i is 2i + 1 and right child of an node i is 2i + 2).

Please let us know if you still have question about this.
